version: ~> 1.0 # needed for imports
import: scala/scala-dev:travis/default.yml

dist: xenial

language: scala

env:
  - ADOPTOPENJDK=11

install:
  - |
    export SBT_OPTS="-Dfile.encoding=UTF-8"
    curl -L --silent "https://raw.githubusercontent.com/sbt/sbt/068700b11ee9a9548fe7b196e814b115f602c031/sbt" > $HOME/sbt
    chmod +x $HOME/sbt && sudo mv $HOME/sbt /usr/local/bin/sbt

script:
  - sbt -v "jarjar/publishLocal" "jarjar/IntegrationTest/test" "+test" "publishLocal;scripted"

matrix:
  include:
  - env: ADOPTOPENJDK=8
  - env: ADOPTOPENJDK=11
